### ISSUE TITLE
About OPF_SOCP Code Review

### ISSUE THREAD

**Issue by JunHyeokPSL** [rafabench/AC-OPF#1]
Hello, 
My name is Junhyeok Kim who receives a lot of help from your OPF Code.

I'm trying to program the AC-OPF with SOCP Convexation by Gurobi-Optimization.
And compare the results with Newton-Rapshon (NN) Power Flow.

While comparing it, 
some operating point get same results between NN power flow and SOCP-OPF.
The others are not.

So, I'm wondering that what can be the problem.

If you can any hints or feedback to me, I'm very glad about it.

My Github repository is https://github.com/JunHyeokPSL/acOPF.

Best regards,
Thanks.

**Comment by rafabench** [comment]
Hi,
I'm glad that my code helped you a lot.

So, when you use a root-finding method to solve the power flow, you find a solution to the non-linear system of equations (AC set). In any convex relaxation, you expand the feasible set to have a convex program and find a global optimum. But the solution found in the expanded set may not be feasible in the non-linear set and what you're seeing in the results is exactly the difference between the solution in the AC set and the SOC - AC set. If you use a non-linear solver like Ipopt, you will probably see the results with a smaller difference.
![image](https://user-images.githubusercontent.com/11084282/168483436-18660a62-7939-49d0-a6a5-4c4812944422.png)

**Comment by JunHyeokPSL** [comment]
Thanks.
You mean, the difference may cause due to the gap between AC solutions and SOC convex solutions, right?

**Comment by rafabench** [comment]
Yes, I believe so. You could test in a smaller example with 3 or 5 buses to see what happens. Also, the solver has a tolerance to the an optimal soltion, you could force Gurobi to solve with a smaller tolerance, but I think it's difficult to get the exactly same solution.

**Comment by JunHyeokPSL** [comment]
Thanks for the fast comments.
I will try to handle the tolerance.
